name: uxmonkey
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65615
title: UX Monkey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#0076bd'
    - '#d1cec8'
    - '#4ea1d8'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.32899573468603194
purpose: []
