name: uxmonkey
favicon: null
layout_spectrum: 0.1187805135268718
typography_spectrum: 0.6543631332460791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.10580031643621624
  lightness: 0.559028351912275
  saturation: 0.1776594768743962
  rhythmicContrast: 0.32899573468603194
purpose: []
